name: sketchpad
description: An experimental redux of the DartPad UI.
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  codemirror: any
  collection: any
  flutter:
    sdk: flutter
  http: any
  protobuf: any
  provider: ^6.0.0
  split_view: ^3.2.0
  url_launcher: any
  url_strategy: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dart_logo_128.png
    - assets/gear-96-dark.png
    - assets/gear-96-light.png
